name: ci pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
    postgres:
      image: postgres:17.4-alpine3.21
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: go_bank
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: checkout the code into the Go module repository
        uses: actions/checkout@v2

      - name: Run tests
        run: make test