name: ci pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: go_bank
        options: >-
          --health-cmd "pg_isready -d go_bank -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
        id: go

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          until pg_isready -h localhost -U postgres; do
            sleep 1
          done
          echo "PostgreSQL is ready!"

      - name: Run Migrations
        run: make migrateup

      - name: Run tests
        run: make test
